# Basic Information 
title: Casper van Engelenburg
position: PhD Researcher
affiliation: Delft University of Technology
affiliation_link: https://www.tudelft.nl/
#affiliation_logo: /assets/img/tudelft_white.png
#email: c.c.j.vanengelenburg (at) tudelft.nl

# Search Engine Optimization (SEO)
keywords: casper van engelenburg , van engelenburg casper, caspervanengelenburg, vanengelenburgcasper
canonical: https://www.tudelft.nl/en/staff/c.c.j.vanengelenburg/
description: I am PhD researcher at the intersection of computer vision, machine learning, and architectural design.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=6QHnxs8kMSwC&hl=en
github_link: https://github.com/caspervanengelenburg/
linkedin: https://www.linkedin.com/in/casper-van-engelenburg-12833213b/

# Images 
avatar: /assets/img/avatar.png

# Footnotes
footnote: My website is based on "minimal light" by Yaoyao Liu.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
